oauth2:
  user:
    google:
      client-id: 123
      client-secret: ${googleOauth2SecretKey}
      redirect-uri: http://localhost:8080/redirect/oauth
    kakao:
      client-id: ca7b2a1700b6028446099e7863956d56
      client-secret: ${kakaoOauth2SecretKey}
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    kakao:
      token-uri: https://www.kakao.com/oauth2.0/token
      user-info-uri: https://www.kakao.com/v1/user/me