spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate.hbm2ddl.auto: validate # H2 1.4.200 버전부터는 hibernate.hbm2ddl.auto 프로퍼티를 사용해야 함
    properties:
      hibernate:
        format_sql: true

jwt:
  member:
    access:
      secret: memberAccessTokenSecretmemberAccessTokenSecretmemberAccessTokenSecretmemberAccessTokenSecretmemberAccessTokenSecret
      exp: 300
    refresh:
      secret: memberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecretmemberRefreshTokenSecret
      exp: 10800

board:
  notice:
    board:
      name: notice

kafka:
  enabled: false

cookie:
  domain: localhost