insert into member (login_id, nickname, password, role) values ('test01', 'test01', 'test01', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test02', 'test02', 'test02', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test03', 'test03', 'test03', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test04', 'test04', 'test04', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test05', 'test05', 'test05', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test06', 'test06', 'test06', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test07', 'test07', 'test07', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test08', 'test08', 'test08', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test09', 'test09', 'test09', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test10', 'test10', 'test10', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test11', 'test11', 'test11', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test12', 'test12', 'test12', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test13', 'test13', 'test13', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test14', 'test14', 'test14', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test15', 'test15', 'test15', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test16', 'test16', 'test16', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test17', 'test17', 'test17', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test18', 'test18', 'test18', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test19', 'test19', 'test19', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('test20', 'test20', 'test20', 'ROLE_USER');
insert into member (login_id, nickname, password, role) values ('delete_target', 'delete_target', 'delete_target', 'ROLE_USER');

insert into board (board_name, is_activated) values ('notice', 1);

insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 01', 'notice content 01', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 02', 'notice content 02', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 03', 'notice content 03', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 04', 'notice content 04', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 05', 'notice content 05', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 06', 'notice content 06', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 07', 'notice content 07', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 08', 'notice content 08', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 09', 'notice content 09', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 10', 'notice content 10', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 11', 'notice content 11', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 12', 'notice content 12', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 13', 'notice content 13', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 14', 'notice content 14', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 15', 'notice content 15', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 16', 'notice content 16', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 17', 'notice content 17', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 18', 'notice content 18', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 19', 'notice content 19', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 20', 'notice content 20', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 21', 'notice content 21', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 22', 'notice content 22', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 23', 'notice content 23', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 24', 'notice content 24', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 25', 'notice content 25', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 26', 'notice content 26', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 27', 'notice content 27', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 28', 'notice content 28', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 29', 'notice content 29', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 30', 'notice content 30', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 31', 'notice content 31', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 32', 'notice content 32', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 33', 'notice content 33', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 34', 'notice content 34', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 35', 'notice content 35', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 36', 'notice content 36', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 37', 'notice content 37', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 38', 'notice content 38', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 39', 'notice content 39', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 40', 'notice content 40', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 41', 'notice content 41', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 42', 'notice content 42', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 43', 'notice content 43', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 44', 'notice content 44', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 45', 'notice content 45', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 46', 'notice content 46', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 47', 'notice content 47', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 48', 'notice content 48', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 49', 'notice content 49', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 50', 'notice content 50', 0);
insert into board_post (board_id, writer_id, title, text_content, has_file) values (1, null, 'notice title 51', 'notice content 51', 0);

insert into room (room_name, is_activated) values ('room01', 0);
insert into room (room_name, is_activated) values ('room02', 0);
insert into room (room_name, is_activated) values ('room03', 0);
insert into room (room_name, is_activated) values ('room04', 0);
insert into room (room_name, is_activated) values ('room05', 0);
insert into room (room_name, is_activated) values ('room06', 0);
insert into room (room_name, is_activated) values ('room07', 0);
insert into room (room_name, is_activated) values ('room08', 0);
insert into room (room_name, is_activated) values ('room09', 0);
insert into room (room_name, is_activated) values ('room10', 0);
insert into room (room_name, is_activated) values ('room11', 0);
insert into room (room_name, is_activated) values ('room12', 0);
insert into room (room_name, is_activated) values ('room13', 0);
insert into room (room_name, is_activated) values ('room14', 0);
insert into room (room_name, is_activated) values ('room15', 0);
insert into room (room_name, is_activated) values ('room16', 0);
insert into room (room_name, is_activated) values ('room17', 0);
insert into room (room_name, is_activated) values ('room18', 0);
insert into room (room_name, is_activated) values ('room19', 0);
insert into room (room_name, is_activated) values ('room20', 0);
insert into room (room_name, is_activated) values ('room21', 0);